pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        dir("/var/lib/jenkins/workspace/demopipelinetask/my-app") {
          sh 'mvn -B -DskipTests clean package'
        }
      }
    }
  }
  post {
    always {
      junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
    }
  }
}
