pipeline {
    agent any
    stages {
        stage ('Compile Stage') {

            steps {
                withMaven {
                    bat 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage ('Testing Stage') {

            steps {
                withMaven {
                    bat 'mvn test'
                }
            }
        }
        stage ('Install Stage') {
            steps {
                withMaven {
                    bat 'mvn install'
                }
            }
        }
    }
}
